### PR TITLE
Play Activity Issue Completed

### PR DESCRIPTION
**Pull request by BrandonGranucci**
# All below activities completed.
- [x] User can see live countdown of how much time left to complete game.
- [x] User can see and interact with keyboard.
- [x] User input impacts/interacts with the visual display of the prompt.
- [x] Upon completion of prompt, player will be moved to results screen, if applicable.
- [x] In background, API is used to generate prompt. [PLEASE NOTE: Elijah did this feature]
- [x] In background, user results are saved in the database & their score is updated.
- [x] Remove ability to copy and paste. (If applicable)

### CODE REVIEW

**Comment by Dawidbtc** [comment]
נחמד אחי!

**Comment by Dawidbtc** [comment]
נחמד אחי!  נחמד אחי!  נחמד אחי!   נחמד אחי!  נחמד אחי!

**Review by mrpavsss — APPROVED** [review]
playing game with ya feelz instead

**Comment by Dawidbtc** [comment]
I'll have two number nines, a number nine large, a number six wit extra dip, a number seven, two number 45s, one wit cheese, and a large soda.

**Pull request merged**
